[project]
name = "qwen3-vl-embedding-8b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pillow>=10.3.0",
    "requests>=2.32.5",
    "torch>=2.1.0",
    "transformers>=4.47.0",
    "accelerate>=0.30.0",
]
